# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class ReportWindow(QtWidgets.QWidget):
    """

    """

    def __init__(self):
        """"""

        super().__init__()

        # self.verticalLayoutWidget = QtWidgets.QWidget(self)
        # self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 220, 400))
        # self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout()

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)

        self.TextReport = QtWidgets.QTextEdit(self)
        self.TextReport.setMinimumSize(QtCore.QSize(200, 380))
        self.TextReport.setObjectName("TextReport")
        self.verticalLayout.addWidget(self.TextReport)

        self.menuBar = QtWidgets.QMenuBar(self)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 220, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.save_file_action = QtWidgets.QAction(self)
        self.save_file_action.setObjectName("save_file_action")
        self.menuFIle.addAction(self.save_file_action)
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.setLayout(self.verticalLayout)

        self.retranslateUi()

    def retranslateUi(self):

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("ReportWindow", "Report"))
        self.TextReport.setReadOnly(True)
        self.TextReport.updateGeometry()
        self.menuFIle.setTitle(_translate("ReportWindow", "File"))
        self.save_file_action.setText(_translate("ReportWindow", "Save file..."))
